#!/bin/bash
# make -k

# make all
dune build 
if [ $? == 0 ] 
then
  
  # rm ./*.cmi
  # rm ./*.o
  rm ./*.cmo
  # rm ./*.cmx

  #./logic
  if [[ $# -eq 0  ]]
  then
    ./_build/default/bin/asm.exe # ocamlrun ./asm.bytes
  else 
    ./_build/default/bin/asm.exe $1 # ocamlrun ./asm.bytes $1
  fi
fi
